In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm  import SVR
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/Users/milan/OneDrive/Documentos/python-ml-course-master/datasets/ads/Advertising.csv")
feature_cols= ["TV","Radio","Newspaper"]
x = data[feature_cols]
y = data["Sales"]

In [3]:
#Crea una variable que contiene un objeto SVR que procesará los datos.
estimador=SVR(kernel="linear")
# Selector es una variable RFE que siguiendo el objeto estimador evaluará que variables pueden ser eliminadas del modelo
selector=RFE(estimador, n_features_to_select=2, step=1)
# .fit() es una función propia de sciKitLearn que ejecuta la regresión que contiene una variable propia de la librería.
# Además es ejecutar fit() se le debe de entregar las variables necesarias para su ejecución
selector=selector.fit(x,y)

In [4]:
# Siguiendo el orden de columnas declaradas en feature_cols se puede observar como Newspaper fue descartado.
feature_cols, selector.support_

(['TV', 'Radio', 'Newspaper'], array([ True,  True, False]))

In [5]:
# además da ranking a las variables según su calidad para el modelo
selector.ranking_

array([1, 1, 2])

In [6]:
# Se recupera la data valida para el modelo
x_predict=data[["TV","Radio"]]
# Se crea un objeto lm que ejecuta la regresión lineal
lm = LinearRegression()
# Con la función .fit() en el modelo para generar lo valores del mismo
lm.fit(x_predict,y)

LinearRegression()

**Se observa como el modelo generá distintos parametros, entro los cuales encontramos:**
* La intercepción (ALFA)
* Los coeficientes de TV y Radio(BETA)
* R^2 (Función .score())
* Capacidad de predecir en base valores usando función . predict()

In [15]:
lm.intercept_,lm.coef_, lm.score(x_predict,y), lm.predict(x_predict)

(2.921099912405138,
 2,
 array([0.04575482, 0.18799423]),
 0.8971942610828956,
 array([20.55546463, 12.34536229, 12.33701773, 17.61711596, 13.22390813,
        12.51208449, 11.71821241, 12.10551553,  3.7093792 , 12.55169696,
         7.0358597 , 17.25652015, 10.60866187,  8.81095051, 18.44466773,
        20.82891539, 12.90386507, 23.24107626,  9.94121476, 14.15384619,
        18.12139161, 14.74206357,  6.51417168, 16.54402663,  8.14035215,
        15.6080206 , 14.96769383, 17.0463346 , 19.39954145,  9.15929748,
        21.64292187, 11.35791808,  7.65045928, 18.83346334,  7.56302763,
        16.99280099, 23.36720719, 15.6258994 ,  9.91257829, 20.4405801 ,
        16.37872122, 17.29870935, 21.5621537 , 13.96692266,  8.9009974 ,
        15.16263814,  8.88644967, 21.69944046, 16.28690268,  8.18162949,
        12.64569407,  9.31962792, 20.66180115, 19.96126242, 20.35512357,
        21.30864743,  8.53774783, 12.76239488, 21.89072858, 18.10746914,
         5.74497097, 22.90418658, 16.78413768